import { Action } from "redux";

export const ActionTypes = {
    //INIT STORE
    INIT_STORE: 'INIT_STORE',

    // GRAMMAR ACTIVITIES
    RECEIVE_GRAMMAR_ACTIVITY_DATA: 'RECEIVE_GRAMMAR_ACTIVITY_DATA',
    NO_GRAMMAR_ACTIVITY_FOUND: 'NO_GRAMMAR_ACTIVITY_FOUND',
    RECEIVE_GRAMMAR_ACTIVITIES_DATA: 'RECEIVE_GRAMMAR_ACTIVITIES_DATA',
    NO_GRAMMAR_ACTIVITIES_FOUND: 'NO_GRAMMAR_ACTIVITIES_FOUND',
    TOGGLE_NEW_LESSON_MODAL: 'TOGGLE_NEW_LESSON_MODAL',
    AWAIT_NEW_LESSON_RESPONSE: 'AWAIT_NEW_LESSON_RESPONSE',
    RECEIVE_NEW_LESSON_RESPONSE: 'RECEIVE_NEW_LESSON_RESPONSE',
    START_LESSON_EDIT: 'START_LESSON_EDIT',
    SUBMIT_LESSON_EDIT: 'SUBMIT_LESSON_EDIT',
    FINISH_LESSON_EDIT: 'FINISH_LESSON_EDIT',
    EDITING_LESSON: 'EDITING_LESSON',
    SUBMITTING_LESSON: 'SUBMITTING_LESSON',

    // QUESTIONS
    RECEIVE_QUESTIONS_DATA: 'RECEIVE_QUESTIONS_DATA',
    NO_QUESTIONS_FOUND: 'NO_QUESTIONS_FOUND',

    // QUESTIONS FOR SESSION
    RECEIVE_QUESTION_DATA: 'RECEIVE_QUESTION_DATA',
    NO_QUESTIONS_FOUND_FOR_SESSION: 'NO_QUESTIONS_FOUND_FOR_SESSION',
    GO_T0_NEXT_QUESTION: 'GO_T0_NEXT_QUESTION',
    SUBMIT_RESPONSE: 'SUBMIT_RESPONSE',

    // SESSIONS
    SET_SESSION: 'SET_SESSION',

    // DISPLAY
    DISPLAY_ERROR: 'DISPLAY_ERROR',
    DISPLAY_MESSAGE: 'DISPLAY_MESSAGE',
    CLEAR_DISPLAY_MESSAGE_AND_ERROR: 'CLEAR_DISPLAY_MESSAGE_AND_ERROR',

    // CONCEPTS
    RECEIVE_CONCEPTS_DATA: 'RECEIVE_CONCEPTS_DATA',

    // RESPONSES
    //
    DELETE_RESPONSE_STATUS: 'DELETE_RESPONSE_STATUS',
    UPDATE_RESPONSE_STATUS: 'UPDATE_RESPONSE_STATUS',
    UPDATE_RESPONSE_DATA: 'UPDATE_RESPONSE_DATA',
    SHOULD_RELOAD_RESPONSES: 'SHOULD_RELOAD_RESPONSES',
    START_RESPONSE_EDIT: 'START_RESPONSE_EDIT',
};
//
export interface IInitStoreAction extends Action {
}
