export const grades = [{"value":"Kindergarten","name":"Kindergarten","label":"Kindergarten"},{"value":"1","name":"1st","label":"1st"},{"value":"2","name":"2nd","label":"2nd"},{"value":"3","name":"3rd","label":"3rd"},{"value":"4","name":"4th","label":"4th"},{"value":"5","name":"5th","label":"5th"},{"value":"6","name":"6th","label":"6th"},{"value":"7","name":"7th","label":"7th"},{"value":"8","name":"8th","label":"8th"},{"value":"9","name":"9th","label":"9th"},{"value":"10","name":"10th","label":"10th"},{"value":"11","name":"11th","label":"11th"},{"value":"12","name":"12th","label":"12th"},{"value":"University","name":"University","label":"University"},{"value":"Other","name":"Other","label":"Other"}]

export const schools = [{"id":58452,"name":"Frelinghuysen Middle","label":"Frelinghuysen Middle","value":58452}]

export const timeframes = [{"value":"last-30-days","name":"Last 30 days","default":true,"label":"Last 30 days"},{"value":"last-90-days","name":"Last 90 days","default":false,"label":"Last 90 days"},{"value":"this-month","name":"This month","default":false,"label":"This month"},{"value":"last-month","name":"Last month","default":false,"label":"Last month"},{"value":"this-year","name":"This year","default":false,"label":"This year"},{"value":"last-year","name":"Last year","default":false,"label":"Last year"},{"value":"all-time","name":"All time","default":false,"label":"All time"},{"value":"custom","name":"Custom","default":false,"label":"Custom"}]

export const teachers = [{"id":1500140,"name":"Brendan Breen","label":"Brendan Breen","value":1500140},{"id":1500832,"name":"Tracey Villaverde","label":"Tracey Villaverde","value":1500832},{"id":3570928,"name":"Joseph Pozzuto","label":"Joseph Pozzuto","value":3570928}]

export const classrooms = [{"id":170171,"name":"Library 01","label":"Library 01","value":170171},{"id":1203848,"name":"English 9 H-Period 9 2021-2022 9","label":"English 9 H-Period 9 2021-2022 9","value":1203848},{"id":1203849,"name":"English 9 H-Period 7 2021 - 2022 7","label":"English 9 H-Period 7 2021 - 2022 7","value":1203849}]
