export default [
  {
    type: 'SF',
    data: {
      isFragment: true,
      prompt: 'Listening to music on the ride home.',
      responses: {
        0: {
          childCount: 2,
          count: 48,
          feedback: "That's a great answer.",
          optimal: true,
          text: 'I listened to music on the ride home.',
          key: '0',
        },
        '-KOuy_LLuYtJ8mVPc6qq': {
          count: 2,
          createdAt: '1470942041444',
          feedback: "That's a great answer",
          optimal: true,
          text: 'She listened to music on the ride home.',
          key: '-KOuy_LLuYtJ8mVPc6qq',
        },
        '-KOv4DgaPIzaB-Kl0Tn-': {
          childCount: 19,
          count: 7,
          createdAt: '1470943783691',
          feedback: "<p>Great job! That's a strong sentence.</p>",
          optimal: true,
          text: 'Peter listened to music on the ride home.',
          weak: false,
          key: '-KOv4DgaPIzaB-Kl0Tn-',
        },
        '-KOv7GQgpZ8Q3NM7Vppv': {
          count: 2,
          createdAt: '1470944581462',
          feedback: "<p>Great job! That's a strong sentence.</p>",
          optimal: true,
          text: 'I listen to music on the ride home.',
          weak: false,
          key: '-KOv7GQgpZ8Q3NM7Vppv',
        },
        '-KOv9w-aaCDxOg7OQ72u': {
          count: 1,
          createdAt: '1470945280179',
          text: 'elephants listened to music on the ride home.',
          key: '-KOv9w-aaCDxOg7OQ72u',
        },
        '-KOv_PhE-yuHWvSMYWeb': {
          count: 1,
          createdAt: '1470952221637',
          text: 'Monkeys listened to music on the ride home.',
          key: '-KOv_PhE-yuHWvSMYWeb',
        },
        '-KOv_XxXgRPjUBGOErg5': {
          count: 1,
          createdAt: '1470952255450',
          text: 'Monkeys listened to music on the ride home.',
          key: '-KOv_XxXgRPjUBGOErg5',
        },
        '-KOvbQahCTyN18SwAc0z': {
          count: 8,
          createdAt: '1470952749605',
          feedback: 'Excellent!',
          optimal: true,
          parentID: '-KOv4DgaPIzaB-Kl0Tn-',
          text: 'Donald listened to music on the ride home.',
          key: '-KOvbQahCTyN18SwAc0z',
        },
        '-KOvdBZRKYoPg21-fcDH': {
          count: 1,
          createdAt: '1470953212302',
          text: "Doesn't exist listened to music.",
          key: '-KOvdBZRKYoPg21-fcDH',
        },
        '-KOvdkiZ7fRFE2ZJOnuM': {
          count: 1,
          createdAt: '1470953360434',
          text: 'Bananas listened to music on the ride home.',
          key: '-KOvdkiZ7fRFE2ZJOnuM',
        },
        '-KOvdr52McwseycHyqij': {
          count: 3,
          createdAt: '1470953386512',
          text: 'Apples listened to music on the ride home.',
          key: '-KOvdr52McwseycHyqij',
        },
        '-KOveNAGXhOnEQRtH45A': {
          count: 3,
          createdAt: '1470953522017',
          feedback: 'Excellent!',
          optimal: true,
          parentID: '-KOv4DgaPIzaB-Kl0Tn-',
          text: 'Ryan listened to music on the ride home.',
          key: '-KOveNAGXhOnEQRtH45A',
        },
        '-KOvfaeFz75UPJgU9e9H': {
          count: 3,
          createdAt: '1470953843518',
          feedback: 'Excellent!',
          optimal: true,
          parentID: '-KOv4DgaPIzaB-Kl0Tn-',
          text: 'Courtney listened to music on the ride home.',
          key: '-KOvfaeFz75UPJgU9e9H',
        },
        '-KOvg76141Dgoimbeuv3': {
          count: 1,
          createdAt: '1470953980501',
          feedback: 'Excellent!',
          optimal: true,
          parentID: '-KOv4DgaPIzaB-Kl0Tn-',
          text: 'Gustav listened to music on the ride home.',
          key: '-KOvg76141Dgoimbeuv3',
        },
        '-KOvgy01JpWu_Ap18L3o': {
          count: 2,
          createdAt: '1470954201293',
          feedback: 'Excellent!',
          optimal: true,
          parentID: '-KOv4DgaPIzaB-Kl0Tn-',
          text: 'Thomas listened to music on the ride home.',
          key: '-KOvgy01JpWu_Ap18L3o',
        },
        '-KOvhAd4iZPGPQoyLTrt': {
          count: 1,
          createdAt: '1470954257105',
          feedback: 'Excellent!',
          optimal: true,
          parentID: '-KOv4DgaPIzaB-Kl0Tn-',
          text: 'Panda listened to music on the ride home.',
          key: '-KOvhAd4iZPGPQoyLTrt',
        },
        '-KOvhFpViauUKyl1lL2G': {
          count: 1,
          createdAt: '1470954278382',
          text: 'No one listens to music, ever.',
          key: '-KOvhFpViauUKyl1lL2G',
        },
        '-KOvhU_hUz3Hz5aMQKUh': {
          count: 1,
          createdAt: '1470954338810',
          text: 'No one listens to piano, ever.',
          key: '-KOvhU_hUz3Hz5aMQKUh',
        },
        '-KOzBwVXthL19KBNUuZ6': {
          count: 1,
          createdAt: '1471012916086',
          text: 'Donald listened to music.',
          key: '-KOzBwVXthL19KBNUuZ6',
        },
        '-KOzH8_qAHB0_YaGfRP_': {
          count: 1,
          createdAt: '1471014280421',
          text: 'Apples listened to music on the ride home.',
          key: '-KOzH8_qAHB0_YaGfRP_',
        },
        '-KOzM3u3Hp8xzdNusjcQ': {
          count: 1,
          createdAt: '1471015571928',
          text: 'Apples listened to music on the rides homes.',
          key: '-KOzM3u3Hp8xzdNusjcQ',
        },
        '-KOzNzZ-ItzxAxQYMSP_': {
          count: 1,
          createdAt: '1471016074329',
          feedback: 'Excellent!',
          optimal: true,
          parentID: '0',
          text: 'Nobody listened to music on the ride home.',
          key: '-KOzNzZ-ItzxAxQYMSP_',
        },
        '-KOzRMW3zOvgX-ZzRyFa': {
          childCount: 2,
          count: 2,
          createdAt: '1471016958955',
          text: 'Listen.',
          key: '-KOzRMW3zOvgX-ZzRyFa',
        },
        '-KOzRRiZQGgkj_XSQ8U7': {
          count: 1,
          createdAt: '1471016980301',
          text: 'Listen to music on the ride home.',
          key: '-KOzRRiZQGgkj_XSQ8U7',
        },
        '-KOzRfU_eRS2yKn9BhWy': {
          count: 1,
          createdAt: '1471017040783',
          text: 'Run.',
          key: '-KOzRfU_eRS2yKn9BhWy',
        },
        '-KOzURn98h6FauB3mEBN': {
          count: 2,
          createdAt: '1471017768837',
          feedback: 'Try writing the sentence in another way.',
          parentID: '-KOzRMW3zOvgX-ZzRyFa',
          text: 'Write.',
          key: '-KOzURn98h6FauB3mEBN',
        },
        '-KOzUXDK3KCxbCh-lAF-': {
          count: 4,
          createdAt: '1471017791056',
          feedback: 'Excellent!',
          optimal: true,
          parentID: '-KOv4DgaPIzaB-Kl0Tn-',
          text: 'John listened to music on the ride home.',
          key: '-KOzUXDK3KCxbCh-lAF-',
        },
        '-KPE_Aj1-mwt-I7K7kFf': {
          count: 1,
          createdAt: '1471287704567',
          feedback: 'Excellent!',
          optimal: true,
          parentID: '-KOv4DgaPIzaB-Kl0Tn-',
          text: 'Jacob listened to music on the ride home.',
          key: '-KPE_Aj1-mwt-I7K7kFf',
        },
        '-KPPcKlt4sD6RZGaJ83O': {
          count: 1,
          createdAt: '1471473081897',
          feedback: 'Excellent!',
          optimal: true,
          parentID: '0',
          text: 'I listened to music on the ride hom.',
          key: '-KPPcKlt4sD6RZGaJ83O',
        },
        '-KPTFz4xCW3ccaRQs2RI': {
          conceptResults: {
            '-KPTKtoxE2UabAeg59Rr': {
              conceptUID: 'iUE6tekeyep8U385dtmVfQ',
              correct: true,
            },
          },
          count: 5,
          createdAt: '1471534068015',
          feedback: "<p>Great job! That's a strong sentence.</p>",
          optimal: true,
          text: 'I am listening to music on the ride home.',
          weak: false,
          key: '-KPTFz4xCW3ccaRQs2RI',
        },
        '-KPTOH7GCExAXUbGCeHH': {
          count: 4,
          createdAt: '1471536243195',
          text: 'a',
          key: '-KPTOH7GCExAXUbGCeHH',
        },
        '-KPTiS-as93XAIOUAV_r': {
          count: 1,
          createdAt: '1471541792518',
          text: 'b',
          key: '-KPTiS-as93XAIOUAV_r',
        },
      },
      key: '-KOqKBMgXHF2dNMM8jhg',
      attempts: [
        {
          found: true,
          submitted: 'I am listening to music on the ride home.',
          posMatch: true,
          exactMatch: true,
          response: {
            conceptResults: {
              '-KPTKtoxE2UabAeg59Rr': {
                conceptUID: 'iUE6tekeyep8U385dtmVfQ',
                correct: true,
              },
            },
            count: 5,
            createdAt: '1471534068015',
            feedback: "<p>Great job! That's a strong sentence.</p>",
            optimal: true,
            text: 'I am listening to music on the ride home.',
            weak: false,
            key: '-KPTFz4xCW3ccaRQs2RI',
          },
        }
      ],
      needsIdentification: true,
      identified: true,
    },
  },
  {
    type: 'SF',
    data: {
      isFragment: false,
      prompt: 'Go away.',
      responses: {
        0: {
          feedback: "That's a great answer.",
          optimal: true,
          text: 'Go away.',
        },
        '-KPPT-gUaVBNLkDvg8YN': {
          count: 1,
          createdAt: '1471470374073',
          text: 'Go away to your home.',
        },
        '-KPPVRhBnAd7M-Jt_YIw': {
          childCount: 4,
          count: 1,
          createdAt: '1471471013162',
          text: 'b',
        },
        '-KPPVhnsvUOTxthrVDmH': {
          childCount: 1,
          count: 1,
          createdAt: '1471471083225',
          text: 'go',
        },
        '-KPPaSl6Lzl_9ch8VjVW': {
          count: 2,
          createdAt: '1471472590359',
          feedback: 'Try writing the sentence in another way.',
          parentID: '-KPPVRhBnAd7M-Jt_YIw',
          text: 'I go away.',
        },
        '-KPTiJ6m2z5p3vzyOsMo': {
          count: 1,
          createdAt: '1471541755936',
          feedback: 'Try writing the sentence in another way.',
          parentID: '-KPPVhnsvUOTxthrVDmH',
          text: 'Get away from me.',
        },
        '-KPTlM7TbP6XU1s9GRTs': {
          count: 2,
          optimal: false,
          createdAt: '1471542555053',
          feedback: 'Try writing the sentence in another way.',
          parentID: '-KPPVRhBnAd7M-Jt_YIw',
          text: 'I want you to go away.',
        },
      },
      key: '-KOqLomeMhOuHqX9Zdqv',
      attempts: [
        {
          found: true,
          submitted: 'I want you to go away.',
          posMatch: true,
          exactMatch: true,
          response: {
            count: 2,
            optimal: false,
            createdAt: '1471542555053',
            feedback: 'Try writing the sentence in another way.',
            parentID: '-KPPVRhBnAd7M-Jt_YIw',
            text: 'I want you to go away.',
            key: '-KPTlM7TbP6XU1s9GRTs',
          },
        }
      ],
      needsIdentification: true,
      identified: false,
    },
  },
  {
    type: 'SC',
    data: {
      conceptID: '-KP-Jqv3V5eGauVBB7tU',
      cues: [
        'after',
        'even though',
        'since'
      ],
      prefilledText: 'Since it was snowing, Marcella wore a sweater.',
      prompt: '<p>It was snowing. Marcella wore a sweater.</p>',
      responses: {
        '-KP-Mm5rEOgKK7nNq6Hd': {
          conceptResults: {
            '-KPP0Ei06JH8NunaU8bZ': {
              conceptUID: '7H2IMZvq0VJ4Uvftyrw7Eg',
              correct: true,
            },
            '-KPP0GTsFlYtAcsv7y1b': {
              conceptUID: 'Q8FfGSv4Z9L2r1CYOfvO9A',
              correct: true,
            },
          },
          count: 7,
          createdAt: '1471032544105',
          feedback: "<p>That's a great sentence!</p>",
          optimal: true,
          text: 'Since it was snowing, Marcella wore a sweater.',
          weak: false,
          key: '-KP-Mm5rEOgKK7nNq6Hd',
        },
        '-KPIvCrIO9KmrB2PRYxC': {
          childCount: 1,
          conceptResults: {
            '-KPP-sGx2GjApwEJhSl6': {
              conceptUID: '7H2IMZvq0VJ4Uvftyrw7Eg',
              correct: true,
            },
            '-KPP-zGt3rNoqb7awfvv': {
              conceptUID: 'nb0JW1r5pRB5ouwAzTgMbQ',
              correct: true,
            },
          },
          count: 13,
          createdAt: '1471360589393',
          feedback: "<p>Great job! That's a strong sentence.</p>",
          optimal: true,
          text: 'Marcella wore a sweater since it was snowing.',
          weak: false,
          key: '-KPIvCrIO9KmrB2PRYxC',
        },
        '-KPQoqC7mi5n7Bp7qd49': {
          count: 1,
          createdAt: '1471493136233',
          text: 'After Marcella wore a sweater since it was snowing.',
          key: '-KPQoqC7mi5n7Bp7qd49',
        },
        '-KPQor0DnpEeSR6015vw': {
          count: 1,
          createdAt: '1471493139576',
          text: 'After Marcella wore a sweater since it was snowing.',
          key: '-KPQor0DnpEeSR6015vw',
        },
        '-KPQosAaHga6hXl1LSD_': {
          count: 1,
          createdAt: '1471493144336',
          text: 'After Marcella wore a sweater since it was snowing.',
          key: '-KPQosAaHga6hXl1LSD_',
        },
        '-KPQpUm2ZbpuDtvvlUYW': {
          author: 'Punctuation Hint',
          count: 1,
          createdAt: '1471493309299',
          feedback: 'There may be an error. How could you update the punctuation?',
          parentID: '-KP-Mm5rEOgKK7nNq6Hd',
          text: 'Since it was snowing Marcella wore a sweater.',
          key: '-KPQpUm2ZbpuDtvvlUYW',
        },
        '-KPQpfJg6sDFgGwhpRjc': {
          conceptResults: {
            '-KPTk-Qp8eMVTvhFjTah': {
              conceptUID: 'OVf1iPpUhc4bVshoDrj9sg',
              correct: false,
            },
            '-KPTk2DKQ-w4ptf4B_mu': {
              conceptUID: 'nb0JW1r5pRB5ouwAzTgMbQ',
              correct: true,
            },
          },
          count: 2,
          createdAt: '1471493354749',
          feedback: '<p><br></p>',
          optimal: false,
          text: 'It was snowing even though Marcella wore a sweater.',
          weak: false,
          key: '-KPQpfJg6sDFgGwhpRjc',
        },
        '-KPQpsFvSGPOxNwcUCmA': {
          author: 'Punctuation Hint',
          count: 1,
          createdAt: '1471493404962',
          feedback: 'There may be an error. How could you update the punctuation?',
          parentID: '-KP-Mm5rEOgKK7nNq6Hd',
          text: 'Since it was snowing Marcella wore a sweater.',
          key: '-KPQpsFvSGPOxNwcUCmA',
        },
        '-KPQpuulZcWaMVVgbkzG': {
          author: 'Word Error Hint',
          count: 1,
          createdAt: '1471493415831',
          feedback: 'Try again. There may be a spelling mistake.',
          parentID: '-KP-Mm5rEOgKK7nNq6Hd',
          text: 'Since it was snowing marcella wore a sweater.',
          key: '-KPQpuulZcWaMVVgbkzG',
        },
        '-KPQpwlPLRyZzJ8pZxVX': {
          author: 'Punctuation Hint',
          count: 1,
          createdAt: '1471493423423',
          feedback: 'There may be an error. How could you update the punctuation?',
          parentID: '-KP-Mm5rEOgKK7nNq6Hd',
          text: 'Since it was snowing Marcella wore a sweater.',
          key: '-KPQpwlPLRyZzJ8pZxVX',
        },
        '-KPQpxU8HUsK-lH637M2': {
          author: 'Punctuation Hint',
          conceptResults: {
            '-KPTjolejeEOWhsy0Qxc': {
              conceptUID: '7H2IMZvq0VJ4Uvftyrw7Eg',
              correct: true,
            },
            '-KPTjqiVJfrotqSJXTn9': {
              conceptUID: 'nb0JW1r5pRB5ouwAzTgMbQ',
              correct: true,
            },
            '-KPTju7IwX_umAnVa53d': {
              conceptUID: 'JVJhNIHGZLbHF6LYw605XA',
              correct: false,
            },
          },
          count: 2,
          createdAt: '1471493429325',
          feedback: '<p>There may be an error. How could you update the punctuation?</p>',
          optimal: false,
          parentID: '-KPIvCrIO9KmrB2PRYxC',
          text: 'Marcella wore a sweater since it was snowing',
          weak: false,
          key: '-KPQpxU8HUsK-lH637M2',
        },
        '-KPQrhhjya320W91RU2S': {
          count: 1,
          createdAt: '1471493891651',
          text: 'Even though it was snowing Marcella wore a sweater.',
          key: '-KPQrhhjya320W91RU2S',
        },
        '-KPQrmKagFzItMrmUMqQ': {
          count: 1,
          createdAt: '1471493910590',
          text: 'Marcella wore a sweater even though it was snowing.',
          key: '-KPQrmKagFzItMrmUMqQ',
        },
        '-KPQrowOPYKQfjdOXFvI': {
          count: 1,
          createdAt: '1471493921266',
          text: 'Marcella wore a sweater ,even though it was snowing.',
          key: '-KPQrowOPYKQfjdOXFvI',
        },
        '-KPQt6V2GnQWMYAnj5NV': {
          count: 1,
          createdAt: '1471494252421',
          text: 'It was snowing after Marcella wore a sweater.',
          key: '-KPQt6V2GnQWMYAnj5NV',
        },
        '-KPQt8EWmHZbWV5G0TFT': {
          count: 1,
          createdAt: '1471494261580',
          text: 'it was snowig after marcella wore a sweater',
          key: '-KPQt8EWmHZbWV5G0TFT',
        },
        '-KPQt8wwybc2uN4tm5GO': {
          count: 1,
          createdAt: '1471494262461',
          text: 'It was snowing after Marcella wore a sweater.',
          key: '-KPQt8wwybc2uN4tm5GO',
        },
        '-KPQt9aYMWocK2RA4DGI': {
          count: 1,
          createdAt: '1471494268701',
          text: 'After it was snowing, Marcella wore a sweater.',
          key: '-KPQt9aYMWocK2RA4DGI',
        },
        '-KPQtApIl2zofnIvJImR': {
          count: 1,
          createdAt: '1471494272197',
          text: 'it was snowing after marcella wore a sweater',
          key: '-KPQtApIl2zofnIvJImR',
        },
        '-KPQtD8p0NGx_1vZ9IU-': {
          author: 'Word Error Hint',
          count: 1,
          createdAt: '1471494283247',
          feedback: 'Try again. There may be a spelling mistake.',
          parentID: '-KPQrhhjya320W91RU2S',
          text: 'Even though it was snowing, Marcella wore a sweater.',
          key: '-KPQtD8p0NGx_1vZ9IU-',
        },
        '-KPQtDPBVkAv2AR4EwFh': {
          count: 1,
          createdAt: '1471494282749',
          text: 'It was snowing after marcella wore a sweater.',
          key: '-KPQtDPBVkAv2AR4EwFh',
        },
        '-KPQtDRg9isLRJ6aBeAS': {
          count: 1,
          createdAt: '1471494284454',
          text: '<p>Even though it was snowing, Marcella wore a sweater.</p>',
          key: '-KPQtDRg9isLRJ6aBeAS',
        },
        '-KPQtLs72ILP-kXMLydB': {
          count: 1,
          createdAt: '1471494317032',
          text: 'Marcella wore a sweater after it was snowing',
          key: '-KPQtLs72ILP-kXMLydB',
        },
        '-KPQtQHN-B7erbjsHkp9': {
          author: 'Word Error Hint',
          count: 1,
          createdAt: '1471494335095',
          feedback: 'Try again. There may be a spelling mistake.',
          parentID: '-KPQrhhjya320W91RU2S',
          text: 'Even though it was snowing Marcella wore a sweater',
          key: '-KPQtQHN-B7erbjsHkp9',
        },
        '-KPQtQagOnID3k1BG_Qu': {
          author: 'Word Error Hint',
          count: 1,
          createdAt: '1471494336398',
          feedback: 'Try again. There may be a spelling mistake.',
          parentID: '-KPQrhhjya320W91RU2S',
          text: 'Even though it was snowing Marcella wore a sweater',
          key: '-KPQtQagOnID3k1BG_Qu',
        },
        '-KPQtQdI_L_7Nk-b9ppe': {
          author: 'Word Error Hint',
          count: 1,
          createdAt: '1471494336565',
          feedback: 'Try again. There may be a spelling mistake.',
          parentID: '-KPQrhhjya320W91RU2S',
          text: 'Even though it was snowing Marcella wore a sweater',
          key: '-KPQtQdI_L_7Nk-b9ppe',
        },
        '-KPQtQg8nTXW9rmhvi-9': {
          author: 'Word Error Hint',
          count: 1,
          createdAt: '1471494336746',
          feedback: 'Try again. There may be a spelling mistake.',
          parentID: '-KPQrhhjya320W91RU2S',
          text: 'Even though it was snowing Marcella wore a sweater',
          key: '-KPQtQg8nTXW9rmhvi-9',
        },
        '-KPQtQjtLDc_MB9SjBOH': {
          author: 'Word Error Hint',
          count: 1,
          createdAt: '1471494336987',
          feedback: 'Try again. There may be a spelling mistake.',
          parentID: '-KPQrhhjya320W91RU2S',
          text: 'Even though it was snowing Marcella wore a sweater',
          key: '-KPQtQjtLDc_MB9SjBOH',
        },
        '-KPQtQoPsQsckagfEabV': {
          author: 'Word Error Hint',
          count: 1,
          createdAt: '1471494337275',
          feedback: 'Try again. There may be a spelling mistake.',
          parentID: '-KPQrhhjya320W91RU2S',
          text: 'Even though it was snowing Marcella wore a sweater',
          key: '-KPQtQoPsQsckagfEabV',
        },
        '-KPQuZnN6cOq2PRj07gc': {
          author: 'Word Error Hint',
          count: 1,
          createdAt: '1471494632087',
          feedback: 'Try again. There may be a spelling mistake.',
          parentID: '-KP-Mm5rEOgKK7nNq6Hd',
          text: 'Since it was snowing,Marcella wore a sweater.',
          key: '-KPQuZnN6cOq2PRj07gc',
        },
        '-KPQud-TDmI0bN0UVcAP': {
          author: 'Word Error Hint',
          count: 1,
          createdAt: '1471494649312',
          feedback: 'Try again. There may be a spelling mistake.',
          parentID: '-KP-Mm5rEOgKK7nNq6Hd',
          text: 'Since it was snowing,Marcella wore a sweater.',
          key: '-KPQud-TDmI0bN0UVcAP',
        },
        '-KPQudQ0SlSufZpRvkNr': {
          count: 1,
          createdAt: '1471494651011',
          text: '<p>Since it was snowing, Marcella wore a sweater.</p>',
          key: '-KPQudQ0SlSufZpRvkNr',
        },
        '-KPQvZi25ILYdVNDPhVJ': {
          author: 'Word Error Hint',
          count: 1,
          createdAt: '1471494900671',
          feedback: 'Try again. There may be a spelling mistake.',
          parentID: '-KPQtLs72ILP-kXMLydB',
          text: 'Marcella wore a sweater after it was snowing.',
          key: '-KPQvZi25ILYdVNDPhVJ',
        },
        '-KPQvZzjm-sBuHu78epC': {
          count: 1,
          createdAt: '1471494901803',
          text: '<p>Marcella wore a sweater after it was snowing.</p>',
          key: '-KPQvZzjm-sBuHu78epC',
        },
        '-KPQvaN_ZEWbx94Ybk8f': {
          author: 'Word Error Hint',
          count: 1,
          createdAt: '1471494907489',
          feedback: 'Try again. There may be a spelling mistake.',
          parentID: '-KPQtLs72ILP-kXMLydB',
          text: 'Marcella wore a sweater after it was snowing.',
          key: '-KPQvaN_ZEWbx94Ybk8f',
        },
        '-KPQx8og4wHc4cMra9d_': {
          author: 'Capitalization Hint',
          count: 1,
          createdAt: '1471495314913',
          feedback: 'Try again. There may be a capitalization error.',
          parentID: '-KP-Mm5rEOgKK7nNq6Hd',
          text: 'Since It was snowing, Marcella wore a sweater.',
          key: '-KPQx8og4wHc4cMra9d_',
        },
        '-KPQxC7CZETZwg1ROv5m': {
          author: 'Punctuation Hint',
          count: 1,
          createdAt: '1471495328453',
          feedback: 'There may be an error. How could you update the punctuation?',
          parentID: '-KP-Mm5rEOgKK7nNq6Hd',
          text: 'Since, it was snowing, Marcella wore a sweater.',
          key: '-KPQxC7CZETZwg1ROv5m',
        },
        '-KPQxG371o61oeX9Momg': {
          count: 1,
          createdAt: '1471495344581',
          text: "Since, it's snowing, Marcella wore a sweater.",
          key: '-KPQxG371o61oeX9Momg',
        },
        '-KPTOmlzG9S98kPvPspA': {
          count: 1,
          createdAt: '1471536377034',
          text: 'I work seater.',
          key: '-KPTOmlzG9S98kPvPspA',
        },
      },
      key: '-KP-Mm-zR8JQcT62iUHW',
      attempts: [
        {
          found: true,
          submitted: 'Marcella wore a sweater since it was snowing.',
          response: {
            childCount: 1,
            conceptResults: {
              '-KPP-sGx2GjApwEJhSl6': {
                conceptUID: '7H2IMZvq0VJ4Uvftyrw7Eg',
                correct: true,
              },
              '-KPP-zGt3rNoqb7awfvv': {
                conceptUID: 'nb0JW1r5pRB5ouwAzTgMbQ',
                correct: true,
              },
            },
            count: 13,
            createdAt: '1471360589393',
            feedback: "<p>Great job! That's a strong sentence.</p>",
            optimal: true,
            text: 'Marcella wore a sweater since it was snowing.',
            weak: false,
            key: '-KPIvCrIO9KmrB2PRYxC',
          },
        }
      ],
    },
  }
];
