# Generated by Django 2.2.5 on 2020-01-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegexRuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_id', models.IntegerField()),
                ('name', models.TextField()),
                ('feedback', models.TextField()),
                ('pass_order', models.TextField(choices=[('first', 'first'), ('second', 'second')])),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex_text', models.TextField()),
                ('regex_rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprehension.RegexRuleSet')),
            ],
        ),
    ]
