# Generated by Django 2.2.5 on 2020-01-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0002_auto_20191220_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitypassage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='activityprompt',
            options={},
        ),
        migrations.AlterField(
            model_name='activity',
            name='passages',
            field=models.ManyToManyField(related_name='activities', through='comprehension.ActivityPassage', to='comprehension.Passage'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='prompts',
            field=models.ManyToManyField(related_name='activities', through='comprehension.ActivityPrompt', to='comprehension.Prompt'),
        ),
        migrations.AlterField(
            model_name='activitypassage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityprompt',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
