# Generated by Django 2.2.5 on 2020-01-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0003_regexruleset_prority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regexruleset',
            old_name='prority',
            new_name='priority',
        ),
    ]
