# Generated by Django 2.2.5 on 2020-01-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0003_auto_20200106_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.TextField()),
                ('compute_region', models.TextField()),
                ('model_id', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='ml_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='comprehension.MLModel'),
        ),
        migrations.CreateModel(
            name='MLFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField()),
                ('combined_labels', models.TextField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ml_feedback', to='comprehension.Prompt')),
            ],
            options={
                'unique_together': {('combined_labels', 'prompt')},
            },
        ),
    ]
