# Generated by Django 2.2.5 on 2020-01-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0003_auto_20200106_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('feedback', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('pass_order', models.TextField(choices=[('first', 'first'), ('second', 'second')])),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_sets', to='comprehension.Prompt')),
            ],
            options={
                'unique_together': {('prompt', 'priority', 'pass_order')},
            },
        ),
    ]
