# Generated by Django 2.2.5 on 2020-01-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0004_auto_20200115_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('feedback', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('pass_order', models.TextField(choices=[('first', 'first'), ('second', 'second')])),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_sets', to='comprehension.Prompt')),
            ],
            options={
                'unique_together': {('prompt', 'priority', 'pass_order')},
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex_text', models.TextField()),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='comprehension.RuleSet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
