# Generated by Django 2.2.5 on 2020-01-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0004_auto_20200115_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlfeedback',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='mlfeedback',
            unique_together={('prompt', 'combined_labels', 'order')},
        ),
    ]
