# Generated by Django 2.2.5 on 2020-02-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0006_auto_20200127_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highlight_text', models.TextField()),
                ('highlight_type', models.TextField(choices=[('passage', 'passage')])),
                ('start_index', models.PositiveIntegerField(default=0)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='highlights', to='comprehension.MLFeedback')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
