# Generated by Django 2.2.5 on 2020-02-05 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0007_highlight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruleset',
            old_name='test_for_contains',
            new_name='is_focus_point',
        ),
    ]
