# Generated by Django 2.2.5 on 2020-02-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0008_auto_20200207_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='labeling_approach',
            field=models.TextField(choices=[('multi_label', 'multi_label'), ('single_label', 'single_label')], default='multi_label'),
        ),
    ]
