# Generated by Django 2.2.5 on 2020-02-19 21:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0009_prompt_labeling_approach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='comprehension.MLFeedback'),
        ),
        migrations.CreateModel(
            name='FeedbackHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.PositiveIntegerField()),
                ('entry', models.TextField()),
                ('feedback', django.contrib.postgres.fields.jsonb.JSONField()),
                ('session_id', models.TextField(blank=True, null=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_history', to='comprehension.Prompt')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
