# Generated by Django 2.2.5 on 2020-05-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0011_auto_20200224_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.TextField()),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prompt_entries', to='comprehension.Prompt')),
            ],
            options={
                'unique_together': {('prompt', 'entry')},
            },
        ),
    ]
