# Generated by Django 2.2.5 on 2020-05-14 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0011_auto_20200224_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='scored_reading_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_reading_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='flag',
            field=models.TextField(choices=[('archived', 'archived'), ('beta', 'beta'), ('draft', 'draft'), ('production', 'production')], default='draft'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='ml_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='comprehension.MLModel'),
        ),
    ]
