# Generated by Django 2.2.5 on 2020-05-15 15:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def change_draft_flag_to_alpha(apps, schema_editor):
    Activity = apps.get_model("comprehension", "Activity")
    Activity.objects.filter(flag='draft').update(flag='alpha')


def change_alpha_flag_to_draft(apps, schema_editor):
    Activity = apps.get_model("comprehension", "Activity")
    Activity.objects.filter(flag='alpha').update(flag='draft')


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0011_auto_20200224_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='scored_reading_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='target_reading_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='flag',
            field=models.TextField(choices=[('alpha', 'alpha'), ('archived', 'archived'), ('beta', 'beta'), ('production', 'production')], default='alpha'),
        ),
        migrations.RunPython(change_draft_flag_to_alpha, reverse_code=change_alpha_flag_to_draft),
        migrations.AlterField(
            model_name='prompt',
            name='ml_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompts', to='comprehension.MLModel'),
        ),
    ]
