# Generated by Django 2.2.5 on 2020-05-20 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0013_promptentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurkingRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turking_rounds', to='comprehension.Activity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
