# Generated by Django 2.2.5 on 2020-05-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0014_auto_20200520_1933'),
        ('comprehension', '0014_turkinground'),
    ]

    operations = [
    ]
