# Generated by Django 2.2.5 on 2020-05-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0014_turkinground'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='rule_sets',
            field=models.ManyToManyField(related_name='prompts', to='comprehension.RuleSet'),
        ),
    ]



