# Generated by Django 2.2.5 on 2020-05-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0015_auto_20200520_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='pass_order',
            field=models.TextField(choices=[('first', 'first'), ('second', 'second')], default='first'),
        ),
    ]
