# Generated by Django 2.2.5 on 2020-05-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0016_transfer_rule_sets_data copy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ruleset',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ruleset',
            name='prompt',
        ),
    ]



