# Generated by Django 2.2.5 on 2020-05-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprehension', '0018_set_default_pass_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turkinground',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turking_rounds', to='comprehension.Activity'),
        ),
    ]
