web: bundle exec puma -C ./config/puma.rb

# Note, using MALLOC_ARENA_MAX=2 based on this article:
# https://github.com/mperham/sidekiq/wiki/Deployment#heroku

worker: PUSHER_APP_ID=325358 PUSHER_KEY=b2cbf247b2e2d930b21d PUSHER_SECRET=81dece75b3f7396a6acf MALLOC_ARENA_MAX=2 bundle exec sidekiq -q critical -q critical_external -q default

reportworker: MALLOC_ARENA_MAX=2 bundle exec sidekiq -q default -q low -q critical -q critical_external

# Backup workers that we can use in case we need to isolate external jobs from the queue
externalworker: PUSHER_APP_ID=325358 PUSHER_KEY=b2cbf247b2e2d930b21d PUSHER_SECRET=81dece75b3f7396a6acf MALLOC_ARENA_MAX=2 bundle exec sidekiq -q critical_external

internalworker: PUSHER_APP_ID=325358 PUSHER_KEY=b2cbf247b2e2d930b21d PUSHER_SECRET=81dece75b3f7396a6acf MALLOC_ARENA_MAX=2 bundle exec sidekiq -q critical -q default
