web: bundle exec puma -C ./config/puma.rb

# Note, using MALLOC_ARENA_MAX=2 based on this article:
# https://github.com/mperham/sidekiq/wiki/Deployment#heroku

worker: MALLOC_ARENA_MAX=2 bundle exec sidekiq -q critical -q default

reportworker: MALLOC_ARENA_MAX=2 bundle exec sidekiq -q default -q low

googleworker: MALLOC_ARENA_MAX=2 bundle exec sidekiq -q google

defaultworker: MALLOC_ARENA_MAX=2 bundle exec sidekiq -q default -q low
