source 'https://rubygems.org'

gem 'rails', '~> 4'
gem 'pg'
gem 'sqlite3', group: :development

gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'turbolinks'
gem 'bootstrap-sass'
gem "compass-rails",    github: "milgner/compass-rails", ref: "1749c06f15dc4b058427e7969810457213647fb8"
gem 'jquery-rails'
gem 'rails-backbone'
gem 'haml_coffee_assets'
gem 'honey-cms'#, path: '../honey-cms'
gem 'honey-auth'#, path: '../honey-auth'
gem 'haml-rails'
gem 'bcrypt-ruby', require: 'bcrypt'
gem 'ancestry'
gem 'kaminari'
gem 'redcarpet'
gem 'carrierwave'
gem 'parslet'
gem 'pry'
gem 'sentry-raven'
