export { hashToCollection } from './hashToCollection'
export { isValidRegex } from './isValidRegex'
export { momentFormatConstants } from './momentFormatConstants'
export { copyToClipboard } from './copyToClipboard'
export { getLatestAttempt } from './getLatestAttempt'
export { getCurrentQuestion, getQuestionsWithAttempts, getFilteredQuestions, getDisplayedText, renderPreviewFeedback } from './activityPreviewHelpers'
export { roundValuesToSeconds, roundMillisecondsToSeconds, } from './timeTrackingSharedFunctions'
export { titleCase } from './titleCase'
export { onMobile } from './onMobile'
export { fillInBlankInputLabel, } from './fillInBlankInputLabel'
export { getIconForActivityClassification } from './getIconForActivityClassification'
export { isTrackableStudentEvent } from './isTrackableStudentEvent'
export { hexToRGBA } from './hexToRGBA'
export { uniqueValuesArray } from './uniqueValuesArray'
export { filterNumbers } from './filterFunctions'
