default:
  open_positions:
    - category: "Partnerships"
      title: "Customer Support Specialist"
      url: "https://www.edsurge.com/jobs/customer-support-specialist-at-quill-org-job-at-quill-org"
