default:
  open_positions:
    -
      category: 'Curriculum'
      title: 'Associate Curriculum Product Manager'
      url: 'https://wellfound.com/l/2yV9kT'
    -
      category: 'Curriculum'
      title: 'Social Studies Curriculum Developer'
      url: 'https://wellfound.com/l/2yXg2x'
