---
:concurrency: <%= ENV.fetch("SIDEKIQ_PROCESS_MAX_THREADS", 5).to_i - 1 %>
staging:
  :concurrency: <%= ENV.fetch("SIDEKIQ_PROCESS_MAX_THREADS", 5).to_i - 1 %>
production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_PROCESS_MAX_THREADS", 5).to_i - 1 %>
:queues:
  - critical
  - default
  - low
