FROM node:7.4.0

RUN apt-get update 
RUN apt-get install -y python-pip libpython-dev
RUN pip install awscli --upgrade --user


# Replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
