# frozen_string_literal: true

env_variable_names = [
  'ADEPT_SCALE_URL',
  'AMPLIFY_SHARED_SECRET_KEY',
  'APP_SECRET',
  'ASSET_SYNC_EXISTING_REMOTE_FILES',
  'ASSET_SYNC_EXISTING_REMOTE_FILES',
  'ASSET_SYNC_MANIFEST',
  'BUILDPACK_URL',
  'CLOUDFRONT_CACHE_URL',
  'DATA_BACKUP_PASSWORD',
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_CONNECT_SERVICE_EMAIL',
  'FIREBASE_DATABASE_URL',
  'FIREBASE_GRAMMAR_API_KEY',
  'FIREBASE_GRAMMAR_AUTH_DOMAIN',
  'FIREBASE_GRAMMAR_DATABASE_URL',
  'FIREBASE_GRAMMAR_STORAGE_BUCKET',
  'FIREBASE_STORAGE_BUCKET',
  'FOLLOWER_DB_HOSTNAME',
  'FOLLOWER_DB_NAME',
  'FOLLOWER_DB_PASSWORD',
  'FOLLOWER_DB_PORT',
  'FOLLOWER_DB_USERNAME',
  'GOLANG_FANOUT_URL',
  'GOOGLE_API_CLIENT_ACCESS_TOKEN',
  'GOOGLE_API_CLIENT_REFRESH_TOKEN',
  'GOOGLE_DRIVE_FOLDER_ID',
  'HEROKU_API_KEY',
  'HEROKU_APP',
  'KEEN_PROJECT_ID',
  'KEEN_READ_KEY',
  'KEEN_WRITE_KEY',
  'LEADER_DB_HOSTNAME',
  'LEADER_DB_NAME',
  'LEADER_DB_PASSWORD',
  'LEADER_DB_PORT',
  'LEADER_DB_USERNAME',
  'MAILCHIMP_API_KEY',
  'MAKARA_REPLICA_READ_PERCENTAGE',
  'S3_DATA_DUMP_BUCKET',
  'SCOUT_KEY',
  'SCOUT_LOG_LEVEL',
  'SCOUT_MONITOR',
  'SENSIBLE_DEFAULTS',
  'SKYLIGHT_KEY',
  'STRIPE_NOTIFICATIONS_EMAIL'
]

def found_in_git?(variable_name)
  command = "git log -G '#{variable_name}' -p --all | grep #{variable_name} -B 10 -A 10"
  `#{command}` != ''
end

env_variable_names.each do |var|
  puts "#{var} in git?  #{found_in_git?(var)}"
end
