version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
      node.data: true
      network.host: 0.0.0.0
      discovery.seed_hosts: []
      cluster.initial_master_nodes: []
    ports:
      - '5433:5432'
    volumes:
      - 'postgres:/var/lib/postgresql9.6/data'

volumes:
  postgres: