version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5433:5432'
    volumes:
      - 'postgres:/var/lib/postgresql9.6/data'

volumes:
  postgres: