source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

# CORE
gem 'puma', '~> 4.3.12'
gem 'rails', '~> 6.1'

# EARLY TO APPLY TO OTHER GEMS
gem 'dotenv-rails', '~> 2.7'

# DB
gem 'activerecord-import', '~> 1.1'
gem 'bulk_insert', '~> 1.9'
gem 'pg', '~> 1.2'
gem 'scenic', '~> 1.5.4'

# QUEUE/CACHING
gem 'connection_pool', '~> 2.2.5'
gem 'dalli', '~> 3.2.2'
gem 'redis', '~> 4.5'
gem "redis-rails", "~> 5.0"
gem "redis-store", "~> 1.9"
gem 'redis-namespace', '~> 1.8'
#gem 'sidekiq-pro', '5.0.0', source: 'http://gems.contribsys.com/'
gem 'sidekiq', '~> 5.2.10'
gem 'sinatra', require: false # Used for the web-based queue management interface

# MIDDLEWARE
gem 'rack-cors', '~> 1.1', require: 'rack/cors'
gem 'rack-attack', '~> 6.5'

# API
gem 'active_model_serializers', '~> 0.10'

# SEARCH
gem 'elasticsearch-model', '~> 6.1.2'
gem 'elasticsearch-rails', '~> 6.1.2'
gem 'kaminari', '~> 1.2'

# OTHER

gem 'newrelic_rpm', '~> 9.3.1'
gem 'rubyzip', '~> 2.3'

# WEBSOCKETS
gem 'pusher', '~> 2.0.3'

# HTTP
gem 'faraday-httpclient', '~> 2.0', '>= 2.0.1'
gem 'httparty', '~> 0.18'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'pry', '~> 0.14.1'
  gem 'rb-readline'
  gem 'rspec-rails'
  gem 'webmock'
  gem 'rubocop'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
end

group :production, :staging do
  gem 'judoscale-rails'
  gem 'judoscale-sidekiq'
end
