source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

# CORE
gem 'puma', '~> 4.3'
gem 'rails', '~> 6.1'

# EARLY TO APPLY TO OTHER GEMS
gem 'dotenv-rails', '~> 2.7'

# DB
gem 'activerecord-import'
gem 'bulk_insert'
gem 'pg', '~> 1.2'
gem 'scenic', '~> 1.5.4'

# QUEUE/CACHING
gem 'connection_pool'
gem 'dalli'
gem 'redis', '~> 4.5'
gem "redis-rails", "~> 5.0"
gem "redis-store", "~> 1.9"
gem 'redis-namespace'
#gem 'sidekiq-pro', '5.0.0', source: 'http://gems.contribsys.com/'
gem 'sidekiq', '~> 5.2.10'
gem 'sinatra', require: false # Used for the web-based queue management interface

# MIDDLEWARE
gem 'rack-cors', require: 'rack/cors'
gem 'rack-attack'
gem 'rails_autoscale_agent'

# API
gem 'active_model_serializers'

# SEARCH
gem 'elasticsearch-model', '~> 5.1'
gem 'elasticsearch-rails', '~> 5.1'
gem 'kaminari'

# OTHER

gem 'newrelic_rpm'
gem 'rubyzip'

# WEBSOCKETS
gem 'pusher', '~> 1.4.3'

# HTTP
gem 'httparty'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '~> 4.8.2'
  gem 'pry', '~> 0.10.4'
  gem 'rb-readline'
  gem 'rspec-rails', '~> 4.0'
  gem 'webmock'
end
