# frozen_string_literal: true

module PublicPagesHelper
  STARTER_DIAGNOSTIC_UNIT_TEMPLATE_ID = 99
  INTERMEDIATE_DIAGNOSTIC_UNIT_TEMPLATE_ID = 100
  ADVANCED_DIAGNOSTIC_UNIT_TEMPLATE_ID = 126
  ELL_STARTER_DIAGNOSTIC_UNIT_TEMPLATE_ID = 154
  ELL_INTERMEDIATE_DIAGNOSTIC_UNIT_TEMPLATE_ID = 299
  ELL_ADVANCED_DIAGNOSTIC_UNIT_TEMPLATE_ID = 300
  PRE_AP_WRITINGS_SKILLS_1_UNIT_TEMPLATE_ID = 194
  PRE_AP_WRITINGS_SKILLS_2_UNIT_TEMPLATE_ID = 195
  AP_WRITINGS_SKILLS_UNIT_TEMPLATE_ID = 193
  SPRING_BOARD_SKILLS_UNIT_TEMPLATE_ID = 253

  def featured_activity_url(activity_id)
    "#{ENV['DEFAULT_URL']}/activities/packs/#{activity_id}"
  end
end
