import { Action } from "redux";

export const ActionTypes = {
    //INIT STORE
    INIT_STORE: 'INIT_STORE',

    // PROOFREADER ACTIVITIES
    RECEIVE_PROOFREADER_ACTIVITY_DATA: 'RECEIVE_PROOFREADER_ACTIVITY_DATA',
    NO_PROOFREADER_ACTIVITY_FOUND: 'NO_PROOFREADER_ACTIVITY_FOUND',

    // QUESTIONS
    // RECEIVE_QUESTION_DATA: 'RECEIVE_QUESTION_DATA',
    // NO_QUESTIONS_FOUND: 'NO_QUESTIONS_FOUND',
    // GO_T0_NEXT_QUESTION: 'GO_T0_NEXT_QUESTION',
    SUBMIT_EDIT: 'SUBMIT_RESPONSE',

    // SESSIONS
    SET_FIREBASE_PASSAGE: 'SET_FIREBASE_PASSAGE',
    SET_PASSAGE: 'SET_PASSAGE',

    // CONCEPTS,
    RECEIVE_CONCEPTS_DATA: 'RECEIVE_CONCEPTS_DATA',
};
//
export interface IInitStoreAction extends Action {
}
