require:
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - "QuillLMS/engines/evidence/spec/dummy/**/*"
    - "QuillLMS/engines/evidence/lib/generators/**/*"
    - "QuillLMS/node_modules/**/*"
    - "QuillLMS/client/node_modules/**/*"

#######################################################################################################################
# CAPYBARA
#######################################################################################################################

Capybara/VisibilityMatcher:
  Enabled: true

#######################################################################################################################
# FACTORY BOT
#######################################################################################################################

FactoryBot/AttributeDefinedStatically:
  Enabled: true

FactoryBot/CreateList:
  Enabled: true

FactoryBot/FactoryClassName:
  Enabled: true

FactoryBot/SyntaxMethods:
  Enabled: true

#######################################################################################################################
# GEMSPEC
#######################################################################################################################

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

# TODO enable this
Gemspec/RequireMFA:
  Enabled: false

#######################################################################################################################
# LAYOUT
#######################################################################################################################

Layout/ArrayAlignment:
  Enabled: true

Layout/AssignmentIndentation:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Layout/ClosingHeredocIndentation:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/DotPosition:
  Enabled: true

Layout/ElseAlignment:
  Enabled: false

Layout/EmptyComment:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EmptyLinesAroundBeginBody:
  Enabled: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true

Layout/EndAlignment:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/HeredocIndentation:
  Enabled: true

Layout/InitialIndentation:
  Enabled: true

Layout/LeadingEmptyLines:
  Enabled: true

Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  Enabled: true

#######################################################################################################################
# LINT
#######################################################################################################################

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true
  AllowedMethods:
    - change
    - not_change

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/BooleanSymbol:
  Enabled: true

# TODO turn back on
Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/ImplicitStringConcatenation:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/InterpolationCheck:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/SendWithMixinArgument:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/SafeNavigationChain:
  Enabled: true

Lint/SuppressedException:
  Enabled: true
  AllowComments: true

# TODO evaluate if this should be turned on
Lint/SymbolConversion:
  Enabled: false

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UriEscapeUnescape:
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

#######################################################################################################################
# METRICS
#######################################################################################################################

Metrics/BlockNesting:
  Max: 4

Metrics/CyclomaticComplexity:
  Max: 7

# TODO temporaily disable since it's outputting too much noise
Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: true
  Max: 448
  Exclude:
    - "QuillLMS/app/models/concerns/teacher.rb"
    - "QuillLMS/app/helpers/pages_helper.rb"
    - "QuillLMS/engines/evidence/spec/controllers/evidence/rules_controller_spec.rb"
    - "QuillLMS/engines/evidence/spec/controllers/evidence/activities_controller_spec.rb"


Metrics/ParameterLists:
  Enabled: true
  Max: 7

#######################################################################################################################
# NAMING
#######################################################################################################################

Naming/AccessorMethodName:
  Enabled: true

Naming/AsciiIdentifiers:
  Enabled: true

Naming/BlockForwarding:
  Enabled: true
  EnforcedStyle: explicit

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodName:
  Enabled: true

Naming/MethodParameterName:
  Enabled: true

Naming/RescuedExceptionsVariableName:
  Enabled: true

Naming/VariableName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

#######################################################################################################################
# RAILS
#######################################################################################################################

Rails/Date:
  Enabled: true

Rails/DurationArithmetic:
  Enabled: true

Rails/TimeZone:
  Enabled: true

#######################################################################################################################
# RSPEC
#######################################################################################################################

RSpec/AroundBlock:
  Enabled: true

RSpec/BeEql:
  Enabled: true

# TODO enable due to https://github.com/rubocop/rubocop-rspec/issues/735#issuecomment-540116917
RSpec/DescribedClassModuleWrapping:
  Enabled: false

RSpec/DescribeSymbol:
  Enabled: true

RSpec/EmptyHook:
  Enabled: true

RSpec/EmptyLineAfterExample:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/ExcessiveDocstringSpacing:
  Enabled: true

RSpec/ExpectOutput:
  Enabled: true

RSpec/Focus:
  Enabled: true

RSpec/HookArgument:
  Enabled: true

RSpec/HooksBeforeExamples:
  Enabled: true

RSpec/IdenticalEqualityAssertion:
  Enabled: true

RSpec/InstanceSpy:
  Enabled: true

RSpec/ItBehavesLike:
  Enabled: true

RSpec/IteratedExpectation:
  Enabled: true

RSpec/LeakyConstantDeclaration:
  Enabled: true

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

RSpec/MissingExampleGroupArgument:
  Enabled: true

RSpec/MultipleSubjects:
  Enabled: true

RSpec/OverwritingSetup:
  Enabled: true

RSpec/Pending:
  Enabled: true

RSpec/RepeatedDescription:
  Enabled: true

RSpec/RepeatedIncludeExample:
  Enabled: true

RSpec/SharedContext:
  Enabled: true

RSpec/Rails/AvoidSetupHook:
  Enabled: true

RSpec/SubjectDeclaration:
  Enabled: true

RSpec/UnspecifiedException:
  Enabled: true

RSpec/VariableDefinition:
  Enabled: true

RSpec/VariableName:
  Enabled: true

RSpec/Yield:
  Enabled: true

#######################################################################################################################
# SECURITY
#######################################################################################################################

Security/Eval:
  Enabled: true

Security/IoMethods:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/Open:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

#######################################################################################################################
# STYLE
#######################################################################################################################

Style/AccessModifierDeclarations:
  Enabled: true
  EnforcedStyle: inline

Style/ArgumentsForwarding:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Style/BarePercentLiterals:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/ClassEqualityComparison:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/ClassVars:
  Enabled: true

# TODO evaluate again; currently too many false positives with ActionController::Parameters
Style/CollectionCompact:
  Enabled: false

Style/CommentAnnotation:
  Enabled: true

Style/CommentedKeyword:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EachWithObject:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/EmptyLiteral:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/FloatDivision:
  Enabled: true

Style/For:
  Enabled: true

Style/FormatStringToken:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/GuardClause:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

# Too many false positivies so disabling
Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/IfInsideElse:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/InverseMethods:
  Enabled: true

Style/Lambda:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/MixinGrouping:
  Enabled: true

Style/MixinUsage:
  Enabled: true

Style/MultilineIfModifier:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/MultipleComparison:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NonNilCheck:
  Enabled: true

Style/Not:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true

Style/OpenStructUse:
  Enabled: true

Style/OrAssignment:
  Enabled: true

Style/ParallelAssignment:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true

Style/Proc:
  Enabled: true

# TODO evaluate if this should be enabled
Style/QuotedSymbols:
  Enabled: false

Style/RaiseArgs:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantCapitalW:
  Enabled: true

Style/RedundantConditional:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: true

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/RedundantSort:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Style/SignalException:
  Enabled: true

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
  Enabled: true

Style/StderrPuts:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/Strip:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/TernaryParentheses:
  Enabled: true

Style/WhileUntilDo:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/UnlessLogicalOperators:
  Enabled: true

Style/ZeroLengthPredicate:
  Enabled: true
