export default {
	// MISC
	FIREBASE: "https://quillconnect.firebaseio.com/",

	// UI FEEDBACK ACTIONS
	DISPLAY_ERROR: "DISPLAY_ERROR",
	DISPLAY_MESSAGE: "DISPLAY_MESSAGE",
	DISMISS_FEEDBACK: "DISMISS_FEEDBACK",

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
	AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

	// CONCEPT ACTIONS
	RECEIVE_CONCEPTS_DATA: "RECEIVE_CONCEPTS_DATA",
	AWAIT_NEW_CONCEPT_RESPONSE: "AWAIT_NEW_CONCEPT_RESPONSE",
	RECEIVE_NEW_CONCEPT_RESPONSE: "RECEIVE_NEW_CONCEPT_RESPONSE",
	START_CONCEPT_EDIT: "START_CONCEPT_EDIT",
	FINISH_CONCEPT_EDIT: "FINISH_CONCEPT_EDIT",
	SUBMIT_CONCEPT_EDIT: "SUBMIT_CONCEPT_EDIT",
	TOGGLE_NEW_CONCEPT_MODAL: "TOGGLE_NEW_CONCEPT_MODAL",

	// CONCEPT STATES
	EDITING_CONCEPT: "EDITING_CONCEPT",
	SUBMITTING_CONCEPT: "SUBMITTING_CONCEPT",

	// QUESTION ACTIONS
	RECEIVE_QUESTIONS_DATA: "RECEIVE_QUESTIONS_DATA",
	AWAIT_NEW_QUESTION_RESPONSE: "AWAIT_NEW_QUESTION_RESPONSE",
	RECEIVE_NEW_QUESTION_RESPONSE: "RECEIVE_NEW_QUESTION_RESPONSE",
	START_QUESTION_EDIT: "START_QUESTION_EDIT",
	FINISH_QUESTION_EDIT: "FINISH_QUESTION_EDIT",
	SUBMIT_QUESTION_EDIT: "SUBMIT_QUESTION_EDIT",
	TOGGLE_NEW_QUESTION_MODAL: "TOGGLE_NEW_QUESTION_MODAL",

	// QUESTION STATES
	EDITING_QUESTION: "EDITING_QUESTION",
	SUBMITTING_QUESTION: "SUBMITTING_QUESTION",

	// QUESTION RESPONSE STATES
	START_RESPONSE_EDIT: "START_RESPONSE_EDIT",
	CANCEL_RESPONSE_EDIT: "CANCEL_RESPONSE_EDIT",
	FINISH_RESPONSE_EDIT: "FINISH_RESPONSE_EDIT",
	SUBMIT_RESPONSE_EDIT: "SUBMIT_RESPONSE_EDIT",
	SUBMITTING_RESPONSE: "SUBMITTING_RESPONSE",
	START_CHILD_RESPONSE_VIEW: "START_CHILD_RESPONSE_VIEW",
	CANCEL_CHILD_RESPONSE_VIEW: "CANCEL_CHILD_RESPONSE_VIEW",
	// PATHWAYS DATA
	RECEIVE_PATHWAYS_DATA: "RECEIVE_PATHWAYS_DATA",
	AWAIT_NEW_PATHWAY_RESPONSE: "AWAIT_NEW_PATHWAY_RESPONSE",
	RECEIVE_NEW_PATHWAY_RESPONSE: "RECEIVE_NEW_PATHWAY_RESPONSE",

	// RESPONSE ACTIONS:
	TOGGLE_EXPAND_SINGLE_RESPONSE:"TOGGLE_EXPAND_SINGLE_RESPONSE"
}
