export default {
	// MISC
	FIREBASE: "https://quillconnect.firebaseio.com/",

	// UI FEEDBACK ACTIONS
	DISPLAY_ERROR: "DISPLAY_ERROR",
	DISPLAY_MESSAGE: "DISPLAY_MESSAGE",
	DISMISS_FEEDBACK: "DISMISS_FEEDBACK",

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
	AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

	// CONCEPT ACTIONS
	RECEIVE_CONCEPTS_DATA: "RECEIVE_CONCEPTS_DATA",
	AWAIT_NEW_CONCEPT_RESPONSE: "AWAIT_NEW_CONCEPT_RESPONSE",
	RECEIVE_NEW_CONCEPT_RESPONSE: "RECEIVE_NEW_CONCEPT_RESPONSE",
	START_CONCEPT_EDIT: "START_CONCEPT_EDIT",
	FINISH_CONCEPT_EDIT: "FINISH_CONCEPT_EDIT",
	SUBMIT_CONCEPT_EDIT: "SUBMIT_CONCEPT_EDIT",

	// CONCEPT STATES
	EDITING_CONCEPT: "EDITING_CONCEPT",
	SUBMITTING_CONCEPT: "SUBMITTING_CONCEPT"
}
