# frozen_string_literal: true

source 'https://rubygems.org'

# Declare your gem's dependencies in evidence.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.
gem 'hotwater' # Fuzzy string matching
gem 'httparty'
gem 'redis'
gem 'redis-namespace'
gem 'redis-rails'

# To use a debugger
gem 'byebug', group: [:development, :test]

group :test do
  gem 'm', '~> 1.5.0'
  gem 'minitest-stub_any_instance'
  gem 'pry-byebug'
  gem 'webmock'
end

group :test, :development do
  gem 'factory_bot_rails', '~> 4.8.2', require: false
  gem 'pry'
  gem 'rspec-rails', '~> 5.0'
  gem 'simplecov'
  gem 'simplecov-json', require: false
end
