FROM ruby:2.5.1




RUN apt-get update -y

# fix invalid byte seq error
# (https://stackoverflow.com/questions/17031651/invalid-byte-sequence-in-us-ascii-argument-error-when-i-run-rake-dbseed-in-ra)
# en_US.UTF-8 not available in ruby docker container, do
# (https://github.com/docker-library/ruby/issues/45)
ENV LANG=C.UTF-8

# Replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Base deps
RUN apt-get install -y autoconf \
  bison build-essential libssl-dev wget \ 
  libyaml-dev libreadline6-dev git-core \
  zlib1g-dev libncurses5-dev curl \
  libffi-dev libgdbm3 libgdbm-dev \
  postgresql-client apt-transport-https

# Install Yarn 😻
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -y
RUN apt-get install -y --no-install-recommends yarn

#Ensure bundler is the right version
RUN gem install bundler

# Install gems from gemfile
COPY services/QuillComprehension/Gemfile /tmp/
COPY services/QuillComprehension/.nvmrc /tmp/
WORKDIR /tmp
RUN ls
RUN bundle install

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash \
  && export NVM_DIR="$HOME/.nvm" \
  && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
  && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" \
  && source ~/.bashrc \
  && . /usr/local/nvm/nvm.sh \
  && nvm install \
  && nvm use
RUN nvm -v
WORKDIR /