FROM ubuntu:16.04


RUN mkdir /haim
WORKDIR /haim

RUN apt-get update -y
RUN apt-get install -y python
RUN apt-get install -y python-pip
RUN apt-get install -y perl
RUN apt-get install -y git
RUN apt-get install -y imagemagick
RUN apt-get install -y vim
RUN mkdir /root/.ssh

