FROM ruby:2.3.1

RUN apt-get update -y
RUN mkdir /root/.ssh

# fix invalid byte seq error
# (https://stackoverflow.com/questions/17031651/invalid-byte-sequence-in-us-ascii-argument-error-when-i-run-rake-dbseed-in-ra)
# en_US.UTF-8 not available in ruby docker container, do
# (https://github.com/docker-library/ruby/issues/45)
ENV LANG=C.UTF-8

# Replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Base deps
RUN apt-get install -y autoconf \
  bison build-essential libssl-dev wget \ 
  libyaml-dev libreadline6-dev git-core \
  zlib1g-dev libncurses5-dev curl \
  libffi-dev libgdbm3 libgdbm-dev \
  postgresql-client

COPY ../../../QuillLMS/Gemfile* /tmp/
WORKDIR /tmp
RUN bundle install

WORKDIR /
## Install nvm and npm (doesn't work in Dockerfile, moved to Jenkinsfile)
# curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash && source ~/.bashrc && nvm install 7.5.0 && nvm use 7.5.0
