export const UNIT_TEMPLATE_NAME = 'unitTemplateName'
export const UNIT_TEMPLATE_ID = 'unitTemplateId'
export const UNIT_NAME = 'unitName'
export const ACTIVITY_IDS_ARRAY = 'activityIdsArray'
export const CLASSROOMS = 'classrooms'
export const UNIT_ID = 'unitId'
export const ANONYMOUS_ASSIGN_UNIT_TEMPLATE_ID = 'anonymousAssignUnitTemplateId'
