import { Action } from "redux";

export const ActionTypes = {
    // INIT STORE
    INIT_STORE: 'INIT_STORE',

    // ACTIVITIES
    RECEIVE_ACTIVITY_DATA: 'RECEIVE_ACTIVITY_DATA',
    NO_ACTIVITY_FOUND: 'NO_ACTIVITY_FOUND',

    // SESSION
    SET_ACTIVITY_SESSION_ID: 'SET_ACTIVITY_SESSION_ID',
    RECORD_FEEDBACK: 'RECORD_FEEDBACK'
};
//
