export default function keysForPOS() { 
  return {
    "CC": "Coord Conjuncn",
    "CD": "Cardinal number",
    "DT": "Determiner",
    "EX": "Existential there",
    "FW": "Foreign Word",
    "IN": "Preposition",
    "JJ": "Adjective",
    "JJR": "Adj., comparative",
    "JJS": "Adj., superlative",
    "LS": "List item marker",
    "MD": "Modal",
    "NN": "Noun, sing. or mass",
    "NNP": "Proper noun, sing.",
    "NNPS": "Proper noun, plural",
    "NNS": "Noun, plural",
    "POS": "Possessive ending",
    "PDT": "Predeterminer",
    "PP$": "Possessive pronoun",
    "PRP": "Personal pronoun",
    "RB": "Adverb",
    "RBR": "Adverb, comparative",
    "RBS": "Adverb, superlative",
    "RP": "Particle",
    "SYM": "Symbol",
    "TO": "ÒtoÓ",
    "UH": "Interjection",
    "VB": "verb, base form",
    "VBD": "verb, past tense",
    "VBG": "verb, gerund",
    "VBN": "verb, past part",
    "VBP": "Verb, present",
    "VBZ": "Verb, present",
    "WDT": "Wh-determiner",
    "WP": "Wh pronoun",
    "WP$": "Possessive-Wh",
    "WRB": "Wh-adverb",
    ",": "Comma",
    ".": "Sent-final punct",
    ":": "Mid-sent punct.",
    "$": "Dollar sign",
    "#": "Pound sign",
    "\"": "quote",
    "(": "Left paren",
    ")": "Right paren"
  }
}
